name: ml
channels:
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - _tflow_select=2.1.0
  - abseil-cpp=20210324.2
  - aiohttp=3.8.5
  - aiosignal=1.2.0
  - astunparse=1.6.3
  - async-timeout=4.0.2
  - attrs=23.1.0
  - blas=1.0
  - blinker=1.6.2
  - brotli-python=1.0.9
  - c-ares=1.19.1
  - ca-certificates=2023.08.22
  - certifi=2023.11.17
  - cffi=1.16.0
  - chardet=4.0.0
  - click=8.1.7
  - cryptography=41.0.3
  - cuda=12.3.1
  - cuda-cccl=12.3.101
  - cuda-command-line-tools=12.3.1
  - cuda-compiler=12.3.1
  - cuda-cudart=12.3.101
  - cuda-cudart-dev=12.3.101
  - cuda-cudart-static=12.3.101
  - cuda-cuobjdump=12.3.101
  - cuda-cupti=12.3.101
  - cuda-cupti-static=12.3.101
  - cuda-cuxxfilt=12.3.101
  - cuda-demo-suite=12.3.101
  - cuda-documentation=12.3.101
  - cuda-driver-dev=12.3.101
  - cuda-gdb=12.3.101
  - cuda-libraries=12.3.1
  - cuda-libraries-dev=12.3.1
  - cuda-libraries-static=12.3.1
  - cuda-nsight=12.3.101
  - cuda-nsight-compute=12.3.1
  - cuda-nvcc=12.3.103
  - cuda-nvdisasm=12.3.101
  - cuda-nvml-dev=12.3.101
  - cuda-nvprof=12.3.101
  - cuda-nvprune=12.3.101
  - cuda-nvrtc=12.3.103
  - cuda-nvrtc-dev=12.3.103
  - cuda-nvrtc-static=12.3.103
  - cuda-nvtx=12.3.101
  - cuda-nvvp=12.3.101
  - cuda-opencl=12.3.101
  - cuda-opencl-dev=12.3.101
  - cuda-profiler-api=12.3.101
  - cuda-runtime=12.3.1
  - cuda-sanitizer-api=12.3.101
  - cuda-toolkit=12.3.1
  - cuda-tools=12.3.1
  - cuda-visual-tools=12.3.1
  - cudatoolkit=11.8.0
  - einops=0.7.0
  - frozenlist=1.4.0
  - gds-tools=1.8.1.2
  - giflib=5.2.1
  - google-pasta=0.2.0
  - grpc-cpp=1.37.1
  - hdf5=1.10.6
  - icu=68.1
  - idna=3.4
  - importlib_metadata=6.0.0
  - intel-openmp=2023.1.0
  - jpeg=9e
  - keras-preprocessing=1.1.2
  - krb5=1.20.1
  - ld_impl_linux-64=2.38
  - libcublas=12.3.4.1
  - libcublas-dev=12.3.4.1
  - libcublas-static=12.3.4.1
  - libcufft=11.0.12.1
  - libcufft-dev=11.0.12.1
  - libcufft-static=11.0.12.1
  - libcufile=1.8.1.2
  - libcufile-dev=1.8.1.2
  - libcufile-static=1.8.1.2
  - libcurand=10.3.4.101
  - libcurand-dev=10.3.4.101
  - libcurand-static=10.3.4.101
  - libcurl=8.2.1
  - libcusolver=11.5.4.101
  - libcusolver-dev=11.5.4.101
  - libcusolver-static=11.5.4.101
  - libcusparse=12.2.0.103
  - libcusparse-dev=12.2.0.103
  - libcusparse-static=12.2.0.103
  - libedit=3.1.20221030
  - libev=4.33
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libllvm14=14.0.6
  - libnghttp2=1.52.0
  - libnpp=12.2.3.2
  - libnpp-dev=12.2.3.2
  - libnpp-static=12.2.3.2
  - libnvjitlink=12.3.101
  - libnvjitlink-dev=12.3.101
  - libnvjpeg=12.3.0.81
  - libnvjpeg-dev=12.3.0.81
  - libnvjpeg-static=12.3.0.81
  - libpng=1.6.39
  - libprotobuf=3.15.8
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - llvmlite=0.41.0
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - multidict=6.0.2
  - ncurses=6.4
  - nsight-compute=2023.3.1.1
  - numba=0.58.0
  - oauthlib=3.2.2
  - openssl=1.1.1w
  - opt_einsum=3.3.0
  - pip=23.3
  - pooch=1.7.0
  - pycparser=2.21
  - pyjwt=2.4.0
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - python=3.8.18
  - python-flatbuffers=1.12
  - python_abi=3.8
  - re2=2021.08.01
  - readline=8.2
  - requests=2.31.0
  - setuptools=68.0.0
  - six=1.16.0
  - snappy=1.1.9
  - sqlite=3.41.2
  - tbb=2021.8.0
  - tensorboard-plugin-wit=1.8.1
  - tensorflow=2.4.1
  - tensorflow-base=2.4.1
  - tk=8.6.12
  - typing_extensions=4.7.1
  - wheel=0.41.2
  - xz=5.4.2
  - yarl=1.8.1
  - zlib=1.2.13
  - pip:
      - absl-py==2.0.0
      - anyio==4.0.0
      - appdirs==1.4.4
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - async-lru==2.0.4
      - babel==2.13.1
      - backcall==0.2.0
      - beautifulsoup4==4.12.2
      - bleach==6.1.0
      - cachetools==5.3.2
      - charset-normalizer==3.3.2
      - comm==0.2.0
      - contourpy==1.1.1
      - cycler==0.12.1
      - debugpy==1.8.0
      - decorator==5.1.1
      - defusedxml==0.7.1
      - docker-pycreds==0.4.0
      - exceptiongroup==1.1.3
      - executing==2.0.1
      - fastcore==1.5.29
      - fastdownload==0.0.7
      - fastjsonschema==2.19.0
      - fastprogress==1.0.3
      - filelock==3.13.1
      - flatbuffers==23.5.26
      - fonttools==4.45.0
      - fqdn==1.5.1
      - fsspec==2023.10.0
      - gast==0.4.0
      - gitdb==4.0.11
      - gitpython==3.1.40
      - google-auth==2.23.4
      - google-auth-oauthlib==0.4.6
      - gputil==1.4.0
      - grpcio==1.59.3
      - h5py==3.10.0
      - importlib-metadata==6.8.0
      - importlib-resources==6.1.1
      - ipykernel==6.26.0
      - ipython==8.12.3
      - isoduration==20.11.0
      - jedi==0.19.1
      - jinja2==3.1.2
      - joblib==1.3.2
      - json5==0.9.14
      - jsonpointer==2.4
      - jsonschema==4.20.0
      - jsonschema-specifications==2023.11.1
      - jupyter-client==8.6.0
      - jupyter-core==5.5.0
      - jupyter-events==0.9.0
      - jupyter-lsp==2.2.0
      - jupyter-server==2.10.1
      - jupyter-server-terminals==0.4.4
      - jupyterlab==4.0.9
      - jupyterlab-pygments==0.2.2
      - jupyterlab-server==2.25.2
      - kaggle==1.5.16
      - keras==2.11.0
      - kiwisolver==1.4.5
      - libclang==16.0.6
      - markdown==3.5.1
      - markupsafe==2.1.3
      - matplotlib==3.7.4
      - matplotlib-inline==0.1.6
      - mistune==3.0.2
      - mlxtend==0.23.0
      - mpmath==1.3.0
      - nbclient==0.9.0
      - nbconvert==7.11.0
      - nbformat==5.9.2
      - nest-asyncio==1.5.8
      - networkx==3.1
      - notebook-shim==0.2.3
      - numpy==1.23.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.3.101
      - nvidia-nvtx-cu12==12.1.105
      - opencv-python==4.8.1.78
      - overrides==7.4.0
      - packaging==23.2
      - pandas==2.0.3
      - pandocfilters==1.5.0
      - parso==0.8.3
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==10.1.0
      - pkgutil-resolve-name==1.3.10
      - platformdirs==4.0.0
      - prometheus-client==0.18.0
      - prompt-toolkit==3.0.41
      - protobuf==3.19.6
      - psutil==5.9.6
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pygments==2.17.1
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - python-graphviz==0.20.1
      - python-json-logger==2.0.7
      - python-slugify==8.0.1
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - pyzmq==25.1.1
      - referencing==0.31.0
      - requests-oauthlib==1.3.1
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.13.1
      - rsa==4.9
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - send2trash==1.8.2
      - sentry-sdk==1.35.0
      - setproctitle==1.3.3
      - smmap==5.0.1
      - sniffio==1.3.0
      - soupsieve==2.5
      - stack-data==0.6.3
      - sympy==1.12
      - tensorboard==2.11.2
      - tensorboard-data-server==0.6.1
      - tensorflow-estimator==2.11.0
      - tensorflow-gpu==2.11.0
      - tensorflow-io-gcs-filesystem==0.34.0
      - termcolor==2.3.0
      - terminado==0.18.0
      - text-unidecode==1.3
      - threadpoolctl==3.2.0
      - tinycss2==1.2.1
      - tomli==2.0.1
      - torch==2.1.1
      - torchaudio==2.1.1
      - torchvision==0.16.1
      - tornado==6.3.3
      - tqdm==4.66.1
      - traitlets==5.13.0
      - triton==2.1.0
      - types-python-dateutil==2.8.19.14
      - typing-extensions==4.8.0
      - tzdata==2023.3
      - uri-template==1.3.0
      - urllib3==2.1.0
      - wandb==0.16.0
      - wcwidth==0.2.10
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.6.4
      - werkzeug==3.0.1
      - wrapt==1.16.0
      - zipp==3.17.0
